### ISSUE TITLE
i try to retrain image_retrueval, but there are some bugs

### ISSUE THREAD

**Issue by shixinlishixinli** [opencv/openvino_training_extensions#135]
hi
i try to retrain image_retrueval, but there are some bugs.  i am sure the weight is right. 
Traceback (most recent call last):
  File "tools/train.py", line 259, in <module>
    main()
  File "tools/train.py", line 168, in main
    assert not args.model_weights
AssertionError
W0821 15:21:01.873234 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer
W0821 15:21:01.873397 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer.iter
W0821 15:21:01.873442 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer.beta_1
W0821 15:21:01.873475 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer.beta_2
W0821 15:21:01.873506 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer.decay
W0821 15:21:01.873533 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-0.kernel
W0821 15:21:01.873562 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-1.gamma
W0821 15:21:01.873590 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-1.beta
W0821 15:21:01.873618 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-2.depthwise_kernel
W0821 15:21:01.873646 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-3.gamma
W0821 15:21:01.873673 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-3.beta
W0821 15:21:01.873701 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-4.kernel
W0821 15:21:01.873729 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-5.gamma
W0821 15:21:01.873757 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-5.beta
W0821 15:21:01.873785 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-6.kernel
W0821 15:21:01.873814 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer's state 'm' for (root).layer_with_weights-7.gamma

best 
lisa shi

**Comment by shixinlishixinli** [comment]
hi 
i change 
"if os.path.exists(args.train_dir):                                     
   latest_checkpoint = tf.train.latest_checkpoint(args.train_dir)     
   if latest_checkpoint:                                              
       assert not args.model_weights                                  
       model.load_weights(latest_checkpoint)                          
       print('loaded', latest_checkpoint)         "
to 
"#if os.path.exists(args.train_dir):                                     
 #    latest_checkpoint = tf.train.latest_checkpoint(args.train_dir)     
 #    if latest_checkpoint:                                              
 #        assert not args.model_weights                                  
 #        model.load_weights(latest_checkpoint)                          
  #        print('loaded', latest_checkpoint) 
"
because i do not have checkpoint
