### ISSUE TITLE
ssd_detector tutorial error

### ISSUE THREAD

**Issue by seanjudgemovidius** [opencv/openvino_training_extensions#142]
Hi,
I tried to retrain an SSD Object Detector using the OpenVino Training Extensions. I was following the below tutorial and I was expecting it to work out of the box,
https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/ssd_detector

 When I try to do the training step with the following command:
```
python3 tools/train.py vlp/config.py
```
I get the below error:
```
Traceback (most recent call last):
File "train.py", line 66, in <module>
tf.app.run(main)
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
_run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
File "/home/sean/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
_run_main(main, args)
File "/home/sean/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
sys.exit(main(argv))
File "train.py", line 61, in main
train(cfg)
File "train.py", line 55, in train
predictor.train(input_fn=input_data.input_fn, steps=config.train.steps, max_steps=config.train.max_steps)
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
loss = self._train_model(input_fn, hooks, saving_listeners)
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
return self._train_model_default(input_fn, hooks, saving_listeners)
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1185, in _train_model_default
input_fn, ModeKeys.TRAIN))
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1022, in _get_features_and_labels_from_input_fn
self._call_input_fn(input_fn, mode))
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1113, in _call_input_fn
return input_fn(**kwargs)
File "/home/sean/work/openvino_model_training/openvino_training_extensions/tensorflow_toolkit/ssd_detector/ssd_detector/trainer.py", line 148, in input_fn
dataset = self.train_dataset.apply(tf.contrib.data.shuffle_and_repeat(buffer_size=self.dataset_size))
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1853, in apply
return DatasetV1Adapter(super(DatasetV1, self).apply(transformation_func))
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1290, in apply
dataset = transformation_func(self)
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow/python/data/experimental/ops/shuffle_ops.py", line 90, in _apply_fn
return _ShuffleAndRepeatDataset(dataset, buffer_size, count, seed)
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow/python/data/experimental/ops/shuffle_ops.py", line 49, in __init__
**dataset_ops.flat_structure(self))
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 4898, in shuffle_and_repeat_dataset
output_shapes=output_shapes, name=name)
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 366, in _apply_op_helper
g = ops._get_graph_from_inputs(_Flatten(keywords.values()))
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6139, in _get_graph_from_inputs
_assert_same_graph(original_graph_element, graph_element)
File "/home/sean/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6075, in _assert_same_graph
(item, original_item))
ValueError: Tensor("buffer_size:0", shape=(), dtype=int64, device=/device:CPU:0) must be from the same graph as Tensor("FlatMapDataset:0", shape=(), dtype=variant).
```
 I have tried googling this error and it seems there are a few similar enough issues. However, I have tried all the possible solutions that I have found online and it still doesn't fix my error. I have also added a number of print statements into the tensorflow files to pinpoint what the problem is and it seems as if it uses one graph for a few iterations and then starts using another graph file (which might be the default?). So does anyone know what I am doing incorrectly? 

Any help would be really appreciated! Thanks.

Regards,
Sean.

My Environment:

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.3
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5         1.14.0
- Python version: python3

**Comment by AlexanderDokuchaev** [comment]
Hi @seanjudgemovidius 
Yes, it's reproduced with TensorFlow => 1.14.0. With older version it's works.
Could you install 1.13.1 and try again?

**Comment by seanjudgemovidius** [comment]
Hi @AlexanderDokuchaev ,

It works with Tensorflow version 1.13.1. Thank you!
