### ISSUE TITLE
error for "Install the NNCF Package"

### ISSUE THREAD

**Issue by dandanli814** [opencv/openvino_training_extensions#270]
Hi, thank you for your job.
After I follow your advice to install the NNCF Package as following,

（1）Clone repository
（2）In the project folder, run python setup.py bdist_wheel to build package
（3）Install package running pip install dist/nncf-1.0-py3-none-any.whl

then I use python to import nncf but I get an error message as following:

>>> import nncf
/search/privateData/anaconda3/envs/python36_nncf/lib/python3.6/site-packages/torch/utils/cpp_extension.py:196: UserWarning:
                               !! WARNING !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (/usr/bin/g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.
See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                              !! WARNING !!
  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
.............
ImportError: /tmp/torch_extensions/quantized_functions_cpu/quantized_functions_cpu.so: undefined symbol: _ZN3c106Symbol14fromQualStringERKSs

I don't know where the problem is, I hope to get your help.
Thank you.

**Comment by AlexanderDokuchaev** [comment]
@AlexKoff88 @vshampor @ljaljushkin

**Comment by vshampor** [comment]
Greetings, @dandanli814!

NNCF ships with source code for HW-accelerated quantization operations, which are compiled into executable code just-in-time, during the first import of the NNCF package. These are then used as PyTorch extension modules. Both GCC and NVCC are invoked during this compilation step, and the compiled extension binaries should be compatible with the base PyTorch binaries distributed in the torch package. 

I personally have not encountered your problem, but I guess that the error output that you posted contains the answer:

**_Your compiler (/usr/bin/g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above._**

Since I am using g++ 7.4.0, this problem never happened to me. I suggest you upgrade your gcc/g++ to more recent versions.

**Comment by dandanli814** [comment]
Hi, thank you for your advice and I update my gcc/g++ version to gcc-4.9/g++ -4.9.
Now there is no previous "!! WARNING !!" , but the error is still the same as following:

>>> import nncf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/search/privateData/NNCF/openvino_training_extensions/pytorch_toolkit/nncf/nncf/__init__.py", line 1, in <module>
    from .quantization import Quantization, SymmetricQuantizer, AsymmetricQuantizer, QuantizedNetwork, \
  File "/search/privateData/NNCF/openvino_training_extensions/pytorch_toolkit/nncf/nncf/quantization/__init__.py", line 1, in <module>
    from .algo import Quantization
  File "/search/privateData/NNCF/openvino_training_extensions/pytorch_toolkit/nncf/nncf/quantization/algo.py", line 19, in <module>
    from .layers import QUANTIZATION_MODULES, QuantizationMode, QuantizerConfig
  File "/search/privateData/NNCF/openvino_training_extensions/pytorch_toolkit/nncf/nncf/quantization/layers.py", line 25, in <module>
    from .quantize_functions import symmetric_quantize, asymmetric_quantize
  File "/search/privateData/NNCF/openvino_training_extensions/pytorch_toolkit/nncf/nncf/quantization/quantize_functions.py", line 17, in <module>
    from .extensions import QuantizedFunctionsCPU, QuantizedFunctionsCUDA
  File "/search/privateData/NNCF/openvino_training_extensions/pytorch_toolkit/nncf/nncf/quantization/extensions.py", line 31, in <module>
    verbose=False
  File "/search/privateData/anaconda3/envs/python36_nncf/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 658, in load
    is_python_module)
  File "/search/privateData/anaconda3/envs/python36_nncf/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 838, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/search/privateData/anaconda3/envs/python36_nncf/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 982, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/search/privateData/anaconda3/envs/python36_nncf/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/search/privateData/anaconda3/envs/python36_nncf/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /tmp/torch_extensions/quantized_functions_cpu/quantized_functions_cpu.so: undefined symbol: _ZN3c106Symbol14fromQualStringERKSs
>>>

Hope you can help me, thank you very much.

**Comment by vshampor** [comment]
@dandanli814, delete the `/tmp/torch_extensions/` folder - it might still contain the old ABI-incompatible binaries compiled during your previous attempt - and try again.

**Comment by dandanli814** [comment]
Yes, the problem has been solved. Thank you very much~
