### ISSUE TITLE
What branch of openvino_training_extensions should be used?

### ISSUE THREAD

**Issue by js333031** [opencv/openvino_training_extensions#284]
I'm using colab and develop branch. Not sure if this is a good branch to use. I get following error when executing "python ../../external/mmdetection/tools/train.py ./configs/person-vehicle-bike-detection-crossroad-1016.py"

```
/content/openvino_training_extensions/pytorch_toolkit/object_detection
2020-04-25 15:35:27,409 - INFO - Distributed training: False
Traceback (most recent call last):
  File "../../external/mmdetection/tools/train.py", line 98, in <module>
    main()
  File "../../external/mmdetection/tools/train.py", line 76, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/content/openvino_training_extensions/external/mmdetection/mmdet/models/builder.py", line 60, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/content/openvino_training_extensions/external/mmdetection/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/content/openvino_training_extensions/external/mmdetection/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
  File "/content/openvino_training_extensions/external/mmdetection/mmdet/models/detectors/single_stage.py", line 23, in __init__
    self.bbox_head = builder.build_head(bbox_head)
  File "/content/openvino_training_extensions/external/mmdetection/mmdet/models/builder.py", line 52, in build_head
    return build(cfg, HEADS)
  File "/content/openvino_training_extensions/external/mmdetection/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/content/openvino_training_extensions/external/mmdetection/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
TypeError: __init__() got an unexpected keyword argument 'depthwise_heads'
```

**Comment by Ilya-Krylov** [comment]
Please make sure that you used proper subomules. Develop is stable branch and it good to use it. 

According to tests everything works http://134.191.240.124/job/ote/job/precommit/job/pt_object_detection/32/execution/node/33/log/

**Comment by js333031** [comment]
I'm using colab. When I do git clone, the mmdetection dir is empty. So I cloned mmdetection as a separate step. See the the two git clone commands below. How do I determine proper submodules are in use? 

```
> !git  clone --progress --verbose  https://github.com/opencv/openvino_training_extensions.git
> %cd /content/openvino_training_extensions/external
> !git clone https://github.com/sovrasov/mmdetection/
```

**Comment by js333031** [comment]
Looks like using git on colab is limited. Trying following fails w/"not a git repository" error
!cd /content/openvino_training_extensions/
!git submodule init

**Comment by js333031** [comment]
This can be used to clone the repo into colab:
%%bash
cd /content
git clone  https://github.com/opencv/openvino_training_extensions.git 
ls
cd openvino_training_extensions
git submodule init
git submodule update
