### ISSUE TITLE
No module named 'mmdet'

### ISSUE THREAD

**Issue by andrekv17** [opencv/openvino_training_extensions#289]
**Describe the bug**
I have an issue with imports in mmdetection while running training model
```
Traceback (most recent call last):
  File "../../external/mmdetection/tools/train.py", line 12, in <module>
    from mmdet import __version__
ModuleNotFoundError: No module named 'mmdet'
```

**Steps to Reproduce**
1. from openvino_training_extensions/pytorch_toolkit/object_detection run "bash init_venv.sh"
2. ". venv/bin/activate"
3. "export MODEL_NAME=person-vehicle-bike-detection-crossroad-1016"
4. "export CONFIGURATION_FILE=./configs/$MODEL_NAME.py"
5. "python ../../external/mmdetection/tools/train.py $CONFIGURATION_FILE"

**Environment:**
 - OS: Linux Ubuntu 18.04 LTS
 - Framework version: PyTorch
 - Python version: 3.6
 - OpenVINO version: 2020.2
 - CUDA/cuDNN version:
 - GPU model and memory:

**Comment by Ilya-Krylov** [comment]
@andrekv17 could you provide log of `bash init_venv.sh` work?

**Comment by andrekv17** [comment]
Okey, no I see, what I didn't install Cuda yet
```
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /home/andrey/Workspace/experiments/openvino_training_extensions/pytorch_toolkit/object_detection/venv/bin/python3.6
Also creating executable in /home/andrey/Workspace/experiments/openvino_training_extensions/pytorch_toolkit/object_detection/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
[setupvars.sh] OpenVINO environment initialized
Collecting matplotlib
  Using cached matplotlib-3.2.1-cp36-cp36m-manylinux1_x86_64.whl (12.4 MB)
Processing /home/andrey/.cache/pip/wheels/fa/11/e9/5d5bec0043cebad7874651692cc97c663f349340ecd41f36aa/mmcv-0.2.16-cp36-cp36m-linux_x86_64.whl
Collecting numpy==1.17.5
  Using cached numpy-1.17.5-cp36-cp36m-manylinux1_x86_64.whl (20.0 MB)
Collecting Pillow<=6.2.2
  Using cached Pillow-6.2.2-cp36-cp36m-manylinux1_x86_64.whl (2.1 MB)
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Processing /home/andrey/.cache/pip/wheels/86/1b/58/c23af2fe683acd8edc15d5a1268f0242be1ff2cf827fe34737/terminaltables-3.1.0-py3-none-any.whl
Collecting torch==1.4
  Using cached torch-1.4.0-cp36-cp36m-manylinux1_x86_64.whl (753.4 MB)
Collecting torchvision==0.5.0
  Using cached torchvision-0.5.0-cp36-cp36m-manylinux1_x86_64.whl (4.0 MB)
Collecting pytorchcv==0.0.55
  Using cached pytorchcv-0.0.55-py2.py3-none-any.whl (390 kB)
Collecting tqdm
  Using cached tqdm-4.45.0-py2.py3-none-any.whl (60 kB)
Collecting onnx==1.6.0
  Using cached onnx-1.6.0-cp36-cp36m-manylinux1_x86_64.whl (4.8 MB)
Collecting onnxruntime==1.1.2
  Using cached onnxruntime-1.1.2-cp36-cp36m-manylinux1_x86_64.whl (3.6 MB)
Collecting lxml
  Using cached lxml-4.5.0-cp36-cp36m-manylinux1_x86_64.whl (5.8 MB)
Processing /home/andrey/.cache/pip/wheels/78/d2/b4/617573279167b9cb8fd3a2d17923ae044d5d213bb552abc1be/albumentations-0.4.5-py3-none-any.whl
Collecting imagecorruptions
  Using cached imagecorruptions-1.1.0-py3-none-any.whl (2.1 MB)
Collecting scikit-learn
  Using cached scikit_learn-0.22.2.post1-cp36-cp36m-manylinux1_x86_64.whl (7.1 MB)
Collecting ninja
  Using cached ninja-1.9.0.post1-py3-none-manylinux1_x86_64.whl (98 kB)
Collecting tensorboard
  Using cached tensorboard-2.2.1-py3-none-any.whl (3.0 MB)
Collecting imagesize==1.2.0
  Using cached imagesize-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting asynctest
  Using cached asynctest-0.13.0-py3-none-any.whl (26 kB)
Collecting codecov
  Using cached codecov-2.0.22-py2.py3-none-any.whl (15 kB)
Collecting flake8
  Using cached flake8-3.7.9-py2.py3-none-any.whl (69 kB)
Collecting isort
  Using cached isort-4.3.21-py2.py3-none-any.whl (42 kB)
Collecting pytest
  Using cached pytest-5.4.1-py3-none-any.whl (246 kB)
Collecting pytest-cov
  Using cached pytest_cov-2.8.1-py2.py3-none-any.whl (18 kB)
Collecting pytest-runner
  Using cached pytest_runner-5.2-py2.py3-none-any.whl (6.8 kB)
Collecting xdoctest>=0.10.0
  Using cached xdoctest-0.12.0-py2.py3-none-any.whl (99 kB)
Collecting yapf
  Using cached yapf-0.30.0-py2.py3-none-any.whl (190 kB)
Collecting kwarray
  Using cached kwarray-0.5.8-py2.py3-none-any.whl (50 kB)
Collecting cython
  Using cached Cython-0.29.17-cp36-cp36m-manylinux1_x86_64.whl (2.1 MB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (88 kB)
Processing /home/andrey/.cache/pip/wheels/a7/c1/ea/cf5bd31012e735dc1dfea3131a2d5eae7978b251083d6247bd/PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl
Collecting addict
  Using cached addict-2.2.1-py3-none-any.whl (3.6 kB)
Collecting opencv-python>=3
  Using cached opencv_python-4.2.0.34-cp36-cp36m-manylinux1_x86_64.whl (28.2 MB)
Collecting requests
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting protobuf
  Using cached protobuf-3.11.3-cp36-cp36m-manylinux1_x86_64.whl (1.3 MB)
Collecting typing-extensions>=3.6.2.1
  Using cached typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Collecting scipy
  Using cached scipy-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (26.1 MB)
Collecting opencv-python-headless>=4.1.1
  Using cached opencv_python_headless-4.2.0.34-cp36-cp36m-manylinux1_x86_64.whl (21.6 MB)
Processing /home/andrey/.cache/pip/wheels/ce/b4/ea/ed7e89421721d66834627a2983c5bc4ce298056d5d3f37049e/imgaug-0.2.6-py3-none-any.whl
Collecting scikit-image>=0.15
  Using cached scikit_image-0.16.2-cp36-cp36m-manylinux1_x86_64.whl (26.5 MB)
Collecting joblib>=0.11
  Using cached joblib-0.14.1-py2.py3-none-any.whl (294 kB)
Requirement already satisfied: setuptools>=41.0.0 in ./venv/lib/python3.6/site-packages (from tensorboard->-r ../../external/mmdetection/requirements/optional.txt (line 5)) (46.1.3)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in ./venv/lib/python3.6/site-packages (from tensorboard->-r ../../external/mmdetection/requirements/optional.txt (line 5)) (0.34.2)
Collecting markdown>=2.6.8
  Using cached Markdown-3.2.1-py2.py3-none-any.whl (88 kB)
Processing /home/andrey/.cache/pip/wheels/c3/af/84/3962a6af7b4ab336e951b7877dcfb758cf94548bb1771e0679/absl_py-0.9.0-py3-none-any.whl
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)
Collecting grpcio>=1.24.3
  Using cached grpcio-1.28.1-cp36-cp36m-manylinux2010_x86_64.whl (2.8 MB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.6.0.post3-py3-none-any.whl (777 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.14.1-py2.py3-none-any.whl (89 kB)
Collecting coverage
  Using cached coverage-5.1-cp36-cp36m-manylinux1_x86_64.whl (227 kB)
Collecting pyflakes<2.2.0,>=2.1.0
  Using cached pyflakes-2.1.1-py2.py3-none-any.whl (59 kB)
Collecting pycodestyle<2.6.0,>=2.5.0
  Using cached pycodestyle-2.5.0-py2.py3-none-any.whl (51 kB)
Collecting entrypoints<0.4.0,>=0.3.0
  Using cached entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Using cached importlib_metadata-1.6.0-py2.py3-none-any.whl (30 kB)
Collecting py>=1.5.0
  Using cached py-1.8.1-py2.py3-none-any.whl (83 kB)
Collecting wcwidth
  Using cached wcwidth-0.1.9-py2.py3-none-any.whl (19 kB)
Collecting attrs>=17.4.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting more-itertools>=4.0.0
  Using cached more_itertools-8.2.0-py3-none-any.whl (43 kB)
Collecting packaging
  Using cached packaging-20.3-py2.py3-none-any.whl (37 kB)
Collecting ubelt
  Using cached ubelt-0.9.1-py2.py3-none-any.whl (126 kB)
Collecting pandas
  Using cached pandas-1.0.3-cp36-cp36m-manylinux1_x86_64.whl (10.0 MB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting imageio>=2.3.0
  Using cached imageio-2.8.0-py3-none-any.whl (3.3 MB)
Collecting PyWavelets>=0.4.0
  Using cached PyWavelets-1.1.1-cp36-cp36m-manylinux1_x86_64.whl (4.4 MB)
Collecting networkx>=2.0
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.1.0-py3-none-any.whl (10 kB)
Collecting rsa<4.1,>=3.1.4
  Using cached rsa-4.0-py2.py3-none-any.whl (38 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting zipp>=0.5
  Using cached zipp-3.1.0-py3-none-any.whl (4.9 kB)
Processing /home/andrey/.cache/pip/wheels/17/b5/3e/8ce33554f56742a00afbe043d72753c2d8997e761e72114b04/ordered_set-3.1.1-py2.py3-none-any.whl
Collecting pytz>=2017.2
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting pyasn1>=0.1.3
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Installing collected packages: pyparsing, six, cycler, python-dateutil, kiwisolver, numpy, matplotlib, pyyaml, addict, opencv-python, urllib3, idna, certifi, chardet, requests, mmcv, Pillow, terminaltables, torch, torchvision, pytorchcv, tqdm, protobuf, typing-extensions, onnx, onnxruntime, lxml, scipy, opencv-python-headless, imageio, PyWavelets, decorator, networkx, scikit-image, imgaug, albumentations, imagecorruptions, joblib, scikit-learn, ninja, markdown, absl-py, oauthlib, requests-oauthlib, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, google-auth-oauthlib, grpcio, tensorboard-plugin-wit, werkzeug, tensorboard, imagesize, asynctest, coverage, codecov, pyflakes, pycodestyle, entrypoints, mccabe, flake8, isort, zipp, importlib-metadata, py, wcwidth, attrs, pluggy, more-itertools, packaging, pytest, pytest-cov, pytest-runner, xdoctest, yapf, ordered-set, ubelt, pytz, pandas, kwarray, cython
Successfully installed Pillow-6.2.2 PyWavelets-1.1.1 absl-py-0.9.0 addict-2.2.1 albumentations-0.4.5 asynctest-0.13.0 attrs-19.3.0 cachetools-4.1.0 certifi-2020.4.5.1 chardet-3.0.4 codecov-2.0.22 coverage-5.1 cycler-0.10.0 cython-0.29.17 decorator-4.4.2 entrypoints-0.3 flake8-3.7.9 google-auth-1.14.1 google-auth-oauthlib-0.4.1 grpcio-1.28.1 idna-2.9 imagecorruptions-1.1.0 imageio-2.8.0 imagesize-1.2.0 imgaug-0.2.6 importlib-metadata-1.6.0 isort-4.3.21 joblib-0.14.1 kiwisolver-1.2.0 kwarray-0.5.8 lxml-4.5.0 markdown-3.2.1 matplotlib-3.2.1 mccabe-0.6.1 mmcv-0.2.16 more-itertools-8.2.0 networkx-2.4 ninja-1.9.0.post1 numpy-1.17.5 oauthlib-3.1.0 onnx-1.6.0 onnxruntime-1.1.2 opencv-python-4.2.0.34 opencv-python-headless-4.2.0.34 ordered-set-3.1.1 packaging-20.3 pandas-1.0.3 pluggy-0.13.1 protobuf-3.11.3 py-1.8.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycodestyle-2.5.0 pyflakes-2.1.1 pyparsing-2.4.7 pytest-5.4.1 pytest-cov-2.8.1 pytest-runner-5.2 python-dateutil-2.8.1 pytorchcv-0.0.55 pytz-2020.1 pyyaml-5.3.1 requests-2.23.0 requests-oauthlib-1.3.0 rsa-4.0 scikit-image-0.16.2 scikit-learn-0.22.2.post1 scipy-1.4.1 six-1.14.0 tensorboard-2.2.1 tensorboard-plugin-wit-1.6.0.post3 terminaltables-3.1.0 torch-1.4.0 torchvision-0.5.0 tqdm-4.45.0 typing-extensions-3.7.4.2 ubelt-0.9.1 urllib3-1.25.9 wcwidth-0.1.9 werkzeug-1.0.1 xdoctest-0.12.0 yapf-0.30.0 zipp-3.1.0
Processing /home/andrey/.cache/pip/wheels/de/63/64/3699be2a9d0ccdb37c7f16329acf3863fd76eda58c39c737af/networkx-2.3-py2.py3-none-any.whl
Requirement already satisfied: decorator>=4.3.0 in ./venv/lib/python3.6/site-packages (from networkx==2.3) (4.4.2)
Installing collected packages: networkx
  Attempting uninstall: networkx
    Found existing installation: networkx 2.4
    Uninstalling networkx-2.4:
      Successfully uninstalled networkx-2.4
Successfully installed networkx-2.3
Collecting opencv-python==4.1.0.25
  Using cached opencv_python-4.1.0.25-cp36-cp36m-manylinux1_x86_64.whl (26.6 MB)
Requirement already satisfied: numpy>=1.11.3 in ./venv/lib/python3.6/site-packages (from opencv-python==4.1.0.25) (1.17.5)
Installing collected packages: opencv-python
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.2.0.34
    Uninstalling opencv-python-4.2.0.34:
      Successfully uninstalled opencv-python-4.2.0.34
Successfully installed opencv-python-4.1.0.25
Processing /home/andrey/.cache/pip/wheels/64/7a/c0/ac8f633d11a5f1a6902c72acb9fa828a2bb3639afba4e94a6c/pycocotools-2.0.0-cp36-cp36m-linux_x86_64.whl
Installing collected packages: pycocotools
Successfully installed pycocotools-2.0.0
Collecting tensorboardX==1.8
  Using cached tensorboardX-1.8-py2.py3-none-any.whl (216 kB)
Requirement already satisfied: protobuf>=3.2.0 in ./venv/lib/python3.6/site-packages (from tensorboardX==1.8) (3.11.3)
Requirement already satisfied: six in ./venv/lib/python3.6/site-packages (from tensorboardX==1.8) (1.14.0)
Requirement already satisfied: numpy in ./venv/lib/python3.6/site-packages (from tensorboardX==1.8) (1.17.5)
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages (from protobuf>=3.2.0->tensorboardX==1.8) (46.1.3)
Installing collected packages: tensorboardX
Successfully installed tensorboardX-1.8
Traceback (most recent call last):
  File "setup.py", line 251, in <module>
    sources=['src/compiling_info.cpp']),
  File "setup.py", line 103, in make_cuda_ext
    raise EnvironmentError('CUDA is required to compile MMDetection!')
OSError: CUDA is required to compile MMDetection!

Activate a virtual environment to start working:
$ . venv/bin/activate
```
